backend/src/Entity/Answers.php
<?php

namespace App\Entity;

use App\Repository\AnswersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnswersRepository::class)]
class Answers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $value = null;

    #[ORM\Column]
    private ?bool $is_correct = null;

    #[ORM\ManyToOne(inversedBy: 'answers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Questions $question = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): static
    {
        $this->value = $value;

        return $this;
    }

    public function isIsCorrect(): ?bool
    {
        return $this->is_correct;
    }

    public function setIsCorrect(bool $is_correct): static
    {
        $this->is_correct = $is_correct;

        return $this;
    }

    public function getQuestion(): ?Questions
    {
        return $this->question;
    }

    public function setQuestion(?Questions $question): static
    {
        $this->question = $question;

        return $this;
    }
}

backend/src/Form/AnswersType.php
<?php

namespace App\Form;

use App\Entity\Answers;
use App\Entity\Questions;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnswersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('value')
            ->add('is_correct')
            ->add('question', EntityType::class, [
                'class' => Questions::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Answers::class,
        ]);
    }
}

backend/src/Controller/AnswersController.php
<?php

namespace App\Controller;

use App\Entity\Answers;
use App\Form\AnswersType;
use App\Repository\AnswersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/answers')]
class AnswersController extends AbstractController
{
    #[Route('/', name: 'app_answers_index', methods: ['GET'])]
    public function index(AnswersRepository $answersRepository): Response
    {
        return $this->render('answers/index.html.twig', [
            'answers' => $answersRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_answers_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $answer = new Answers();
        $form = $this->createForm(AnswersType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('app_answers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answers/new.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answers_show', methods: ['GET'])]
    public function show(Answers $answer): Response
    {
        return $this->render('answers/show.html.twig', [
            'answer' => $answer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_answers_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Answers $answer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnswersType::class, $answer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_answers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('answers/edit.html.twig', [
            'answer' => $answer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_answers_delete', methods: ['POST'])]
    public function delete(Request $request, Answers $answer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$answer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($answer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_answers_index', [], Response::HTTP_SEE_OTHER);
    }
}

backend/templates/answers/_delete_form.html.twig
<form method="post" action="{{ path('app_answers_delete', {'id': answer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ answer.id) }}">
    <button class="btn">Delete</button>
</form>

backend/templates/answers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

backend/templates/answers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Answers{% endblock %}

{% block body %}
    <h1>Edit Answers</h1>

    {{ include('answers/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_answers_index') }}">back to list</a>

    {{ include('answers/_delete_form.html.twig') }}
{% endblock %}

backend/templates/answers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answers index{% endblock %}

{% block body %}
    <h1>Answers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Value</th>
                <th>Is_correct</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for answer in answers %}
            <tr>
                <td>{{ answer.id }}</td>
                <td>{{ answer.value }}</td>
                <td>{{ answer.isCorrect ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_answers_show', {'id': answer.id}) }}">show</a>
                    <a href="{{ path('app_answers_edit', {'id': answer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_answers_new') }}">Create new</a>
{% endblock %}

backend/templates/answers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Answers{% endblock %}

{% block body %}
    <h1>Create new Answers</h1>

    {{ include('answers/_form.html.twig') }}

    <a href="{{ path('app_answers_index') }}">back to list</a>
{% endblock %}

backend/templates/answers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Answers{% endblock %}

{% block body %}
    <h1>Answers</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ answer.id }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ answer.value }}</td>
            </tr>
            <tr>
                <th>Is_correct</th>
                <td>{{ answer.isCorrect ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_answers_index') }}">back to list</a>

    <a href="{{ path('app_answers_edit', {'id': answer.id}) }}">edit</a>

    {{ include('answers/_delete_form.html.twig') }}
{% endblock %}